package ivs.thai.model;

public class AppRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_role.role_id
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_role.role_name
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String roleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_role.role_id
	 * @return  the value of app_role.role_id
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_role.role_id
	 * @param roleId  the value for app_role.role_id
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_role.role_name
	 * @return  the value of app_role.role_name
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_role.role_name
	 * @param roleName  the value for app_role.role_name
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}