package ivs.thai.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.Iterator;

public class NhanvienExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public NhanvienExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andManvIsNull() {
			addCriterion("manv is null");
			return (Criteria) this;
		}

		public Criteria andManvIsNotNull() {
			addCriterion("manv is not null");
			return (Criteria) this;
		}

		public Criteria andManvEqualTo(String value) {
			addCriterion("manv =", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvNotEqualTo(String value) {
			addCriterion("manv <>", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvGreaterThan(String value) {
			addCriterion("manv >", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvGreaterThanOrEqualTo(String value) {
			addCriterion("manv >=", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvLessThan(String value) {
			addCriterion("manv <", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvLessThanOrEqualTo(String value) {
			addCriterion("manv <=", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvLike(String value) {
			addCriterion("manv like", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvNotLike(String value) {
			addCriterion("manv not like", value, "manv");
			return (Criteria) this;
		}

		public Criteria andManvIn(List<String> values) {
			addCriterion("manv in", values, "manv");
			return (Criteria) this;
		}

		public Criteria andManvNotIn(List<String> values) {
			addCriterion("manv not in", values, "manv");
			return (Criteria) this;
		}

		public Criteria andManvBetween(String value1, String value2) {
			addCriterion("manv between", value1, value2, "manv");
			return (Criteria) this;
		}

		public Criteria andManvNotBetween(String value1, String value2) {
			addCriterion("manv not between", value1, value2, "manv");
			return (Criteria) this;
		}

		public Criteria andHotenIsNull() {
			addCriterion("hoten is null");
			return (Criteria) this;
		}

		public Criteria andHotenIsNotNull() {
			addCriterion("hoten is not null");
			return (Criteria) this;
		}

		public Criteria andHotenEqualTo(String value) {
			addCriterion("hoten =", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenNotEqualTo(String value) {
			addCriterion("hoten <>", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenGreaterThan(String value) {
			addCriterion("hoten >", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenGreaterThanOrEqualTo(String value) {
			addCriterion("hoten >=", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenLessThan(String value) {
			addCriterion("hoten <", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenLessThanOrEqualTo(String value) {
			addCriterion("hoten <=", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenLike(String value) {
			addCriterion("hoten like", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenNotLike(String value) {
			addCriterion("hoten not like", value, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenIn(List<String> values) {
			addCriterion("hoten in", values, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenNotIn(List<String> values) {
			addCriterion("hoten not in", values, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenBetween(String value1, String value2) {
			addCriterion("hoten between", value1, value2, "hoten");
			return (Criteria) this;
		}

		public Criteria andHotenNotBetween(String value1, String value2) {
			addCriterion("hoten not between", value1, value2, "hoten");
			return (Criteria) this;
		}

		public Criteria andGioitinhIsNull() {
			addCriterion("gioitinh is null");
			return (Criteria) this;
		}

		public Criteria andGioitinhIsNotNull() {
			addCriterion("gioitinh is not null");
			return (Criteria) this;
		}

		public Criteria andGioitinhEqualTo(Boolean value) {
			addCriterion("gioitinh =", value, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhNotEqualTo(Boolean value) {
			addCriterion("gioitinh <>", value, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhGreaterThan(Boolean value) {
			addCriterion("gioitinh >", value, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhGreaterThanOrEqualTo(Boolean value) {
			addCriterion("gioitinh >=", value, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhLessThan(Boolean value) {
			addCriterion("gioitinh <", value, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhLessThanOrEqualTo(Boolean value) {
			addCriterion("gioitinh <=", value, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhIn(List<Boolean> values) {
			addCriterion("gioitinh in", values, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhNotIn(List<Boolean> values) {
			addCriterion("gioitinh not in", values, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhBetween(Boolean value1, Boolean value2) {
			addCriterion("gioitinh between", value1, value2, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andGioitinhNotBetween(Boolean value1, Boolean value2) {
			addCriterion("gioitinh not between", value1, value2, "gioitinh");
			return (Criteria) this;
		}

		public Criteria andHinhanhIsNull() {
			addCriterion("hinhanh is null");
			return (Criteria) this;
		}

		public Criteria andHinhanhIsNotNull() {
			addCriterion("hinhanh is not null");
			return (Criteria) this;
		}

		public Criteria andHinhanhEqualTo(String value) {
			addCriterion("hinhanh =", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhNotEqualTo(String value) {
			addCriterion("hinhanh <>", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhGreaterThan(String value) {
			addCriterion("hinhanh >", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhGreaterThanOrEqualTo(String value) {
			addCriterion("hinhanh >=", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhLessThan(String value) {
			addCriterion("hinhanh <", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhLessThanOrEqualTo(String value) {
			addCriterion("hinhanh <=", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhLike(String value) {
			addCriterion("hinhanh like", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhNotLike(String value) {
			addCriterion("hinhanh not like", value, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhIn(List<String> values) {
			addCriterion("hinhanh in", values, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhNotIn(List<String> values) {
			addCriterion("hinhanh not in", values, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhBetween(String value1, String value2) {
			addCriterion("hinhanh between", value1, value2, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andHinhanhNotBetween(String value1, String value2) {
			addCriterion("hinhanh not between", value1, value2, "hinhanh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhIsNull() {
			addCriterion("ngaysinh is null");
			return (Criteria) this;
		}

		public Criteria andNgaysinhIsNotNull() {
			addCriterion("ngaysinh is not null");
			return (Criteria) this;
		}

		public Criteria andNgaysinhEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh =", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhNotEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh <>", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhGreaterThan(Date value) {
			addCriterionForJDBCDate("ngaysinh >", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh >=", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhLessThan(Date value) {
			addCriterionForJDBCDate("ngaysinh <", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("ngaysinh <=", value, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhIn(List<Date> values) {
			addCriterionForJDBCDate("ngaysinh in", values, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhNotIn(List<Date> values) {
			addCriterionForJDBCDate("ngaysinh not in", values, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ngaysinh between", value1, value2, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andNgaysinhNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("ngaysinh not between", value1, value2, "ngaysinh");
			return (Criteria) this;
		}

		public Criteria andLuongIsNull() {
			addCriterion("luong is null");
			return (Criteria) this;
		}

		public Criteria andLuongIsNotNull() {
			addCriterion("luong is not null");
			return (Criteria) this;
		}

		public Criteria andLuongEqualTo(Double value) {
			addCriterion("luong =", value, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongNotEqualTo(Double value) {
			addCriterion("luong <>", value, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongGreaterThan(Double value) {
			addCriterion("luong >", value, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongGreaterThanOrEqualTo(Double value) {
			addCriterion("luong >=", value, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongLessThan(Double value) {
			addCriterion("luong <", value, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongLessThanOrEqualTo(Double value) {
			addCriterion("luong <=", value, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongIn(List<Double> values) {
			addCriterion("luong in", values, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongNotIn(List<Double> values) {
			addCriterion("luong not in", values, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongBetween(Double value1, Double value2) {
			addCriterion("luong between", value1, value2, "luong");
			return (Criteria) this;
		}

		public Criteria andLuongNotBetween(Double value1, Double value2) {
			addCriterion("luong not between", value1, value2, "luong");
			return (Criteria) this;
		}

		public Criteria andCapdoIsNull() {
			addCriterion("capdo is null");
			return (Criteria) this;
		}

		public Criteria andCapdoIsNotNull() {
			addCriterion("capdo is not null");
			return (Criteria) this;
		}

		public Criteria andCapdoEqualTo(Byte value) {
			addCriterion("capdo =", value, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoNotEqualTo(Byte value) {
			addCriterion("capdo <>", value, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoGreaterThan(Byte value) {
			addCriterion("capdo >", value, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoGreaterThanOrEqualTo(Byte value) {
			addCriterion("capdo >=", value, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoLessThan(Byte value) {
			addCriterion("capdo <", value, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoLessThanOrEqualTo(Byte value) {
			addCriterion("capdo <=", value, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoIn(List<Byte> values) {
			addCriterion("capdo in", values, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoNotIn(List<Byte> values) {
			addCriterion("capdo not in", values, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoBetween(Byte value1, Byte value2) {
			addCriterion("capdo between", value1, value2, "capdo");
			return (Criteria) this;
		}

		public Criteria andCapdoNotBetween(Byte value1, Byte value2) {
			addCriterion("capdo not between", value1, value2, "capdo");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andDienthoaiIsNull() {
			addCriterion("dienthoai is null");
			return (Criteria) this;
		}

		public Criteria andDienthoaiIsNotNull() {
			addCriterion("dienthoai is not null");
			return (Criteria) this;
		}

		public Criteria andDienthoaiEqualTo(String value) {
			addCriterion("dienthoai =", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiNotEqualTo(String value) {
			addCriterion("dienthoai <>", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiGreaterThan(String value) {
			addCriterion("dienthoai >", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiGreaterThanOrEqualTo(String value) {
			addCriterion("dienthoai >=", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiLessThan(String value) {
			addCriterion("dienthoai <", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiLessThanOrEqualTo(String value) {
			addCriterion("dienthoai <=", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiLike(String value) {
			addCriterion("dienthoai like", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiNotLike(String value) {
			addCriterion("dienthoai not like", value, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiIn(List<String> values) {
			addCriterion("dienthoai in", values, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiNotIn(List<String> values) {
			addCriterion("dienthoai not in", values, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiBetween(String value1, String value2) {
			addCriterion("dienthoai between", value1, value2, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andDienthoaiNotBetween(String value1, String value2) {
			addCriterion("dienthoai not between", value1, value2, "dienthoai");
			return (Criteria) this;
		}

		public Criteria andGhichuIsNull() {
			addCriterion("ghichu is null");
			return (Criteria) this;
		}

		public Criteria andGhichuIsNotNull() {
			addCriterion("ghichu is not null");
			return (Criteria) this;
		}

		public Criteria andGhichuEqualTo(String value) {
			addCriterion("ghichu =", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuNotEqualTo(String value) {
			addCriterion("ghichu <>", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuGreaterThan(String value) {
			addCriterion("ghichu >", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuGreaterThanOrEqualTo(String value) {
			addCriterion("ghichu >=", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuLessThan(String value) {
			addCriterion("ghichu <", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuLessThanOrEqualTo(String value) {
			addCriterion("ghichu <=", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuLike(String value) {
			addCriterion("ghichu like", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuNotLike(String value) {
			addCriterion("ghichu not like", value, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuIn(List<String> values) {
			addCriterion("ghichu in", values, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuNotIn(List<String> values) {
			addCriterion("ghichu not in", values, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuBetween(String value1, String value2) {
			addCriterion("ghichu between", value1, value2, "ghichu");
			return (Criteria) this;
		}

		public Criteria andGhichuNotBetween(String value1, String value2) {
			addCriterion("ghichu not between", value1, value2, "ghichu");
			return (Criteria) this;
		}

		public Criteria andMapbIsNull() {
			addCriterion("mapb is null");
			return (Criteria) this;
		}

		public Criteria andMapbIsNotNull() {
			addCriterion("mapb is not null");
			return (Criteria) this;
		}

		public Criteria andMapbEqualTo(String value) {
			addCriterion("mapb =", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbNotEqualTo(String value) {
			addCriterion("mapb <>", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbGreaterThan(String value) {
			addCriterion("mapb >", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbGreaterThanOrEqualTo(String value) {
			addCriterion("mapb >=", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbLessThan(String value) {
			addCriterion("mapb <", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbLessThanOrEqualTo(String value) {
			addCriterion("mapb <=", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbLike(String value) {
			addCriterion("mapb like", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbNotLike(String value) {
			addCriterion("mapb not like", value, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbIn(List<String> values) {
			addCriterion("mapb in", values, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbNotIn(List<String> values) {
			addCriterion("mapb not in", values, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbBetween(String value1, String value2) {
			addCriterion("mapb between", value1, value2, "mapb");
			return (Criteria) this;
		}

		public Criteria andMapbNotBetween(String value1, String value2) {
			addCriterion("mapb not between", value1, value2, "mapb");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table nhanvien
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 08 16:31:42 ICT 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}