package ivs.thai.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.NumberFormat;

public class Nhanvien {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.manv
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String manv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.hoten
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String hoten;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.gioitinh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private Boolean gioitinh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.hinhanh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String hinhanh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.ngaysinh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date ngaysinh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.luong
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	@NumberFormat(pattern = "#,###,###,###")
	private Double luong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.capdo
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private Byte capdo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.email
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.dienthoai
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String dienthoai;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.ghichu
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String ghichu;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column nhanvien.mapb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String mapb;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.manv
	 * @return  the value of nhanvien.manv
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getManv() {
		return manv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.manv
	 * @param manv  the value for nhanvien.manv
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setManv(String manv) {
		this.manv = manv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.hoten
	 * @return  the value of nhanvien.hoten
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getHoten() {
		return hoten;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.hoten
	 * @param hoten  the value for nhanvien.hoten
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.gioitinh
	 * @return  the value of nhanvien.gioitinh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Boolean getGioitinh() {
		return gioitinh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.gioitinh
	 * @param gioitinh  the value for nhanvien.gioitinh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setGioitinh(Boolean gioitinh) {
		this.gioitinh = gioitinh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.hinhanh
	 * @return  the value of nhanvien.hinhanh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getHinhanh() {
		return hinhanh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.hinhanh
	 * @param hinhanh  the value for nhanvien.hinhanh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.ngaysinh
	 * @return  the value of nhanvien.ngaysinh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Date getNgaysinh() {
		return ngaysinh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.ngaysinh
	 * @param ngaysinh  the value for nhanvien.ngaysinh
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.luong
	 * @return  the value of nhanvien.luong
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Double getLuong() {
		return luong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.luong
	 * @param luong  the value for nhanvien.luong
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setLuong(Double luong) {
		this.luong = luong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.capdo
	 * @return  the value of nhanvien.capdo
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Byte getCapdo() {
		return capdo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.capdo
	 * @param capdo  the value for nhanvien.capdo
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setCapdo(Byte capdo) {
		this.capdo = capdo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.email
	 * @return  the value of nhanvien.email
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.email
	 * @param email  the value for nhanvien.email
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.dienthoai
	 * @return  the value of nhanvien.dienthoai
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getDienthoai() {
		return dienthoai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.dienthoai
	 * @param dienthoai  the value for nhanvien.dienthoai
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setDienthoai(String dienthoai) {
		this.dienthoai = dienthoai;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.ghichu
	 * @return  the value of nhanvien.ghichu
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getGhichu() {
		return ghichu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.ghichu
	 * @param ghichu  the value for nhanvien.ghichu
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column nhanvien.mapb
	 * @return  the value of nhanvien.mapb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getMapb() {
		return mapb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column nhanvien.mapb
	 * @param mapb  the value for nhanvien.mapb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setMapb(String mapb) {
		this.mapb = mapb;
	}
}