package ivs.thai.model;

public class Phongban {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phongban.mapb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String mapb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column phongban.tenpb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String tenpb;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phongban.mapb
	 * @return  the value of phongban.mapb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getMapb() {
		return mapb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phongban.mapb
	 * @param mapb  the value for phongban.mapb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setMapb(String mapb) {
		this.mapb = mapb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column phongban.tenpb
	 * @return  the value of phongban.tenpb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getTenpb() {
		return tenpb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column phongban.tenpb
	 * @param tenpb  the value for phongban.tenpb
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setTenpb(String tenpb) {
		this.tenpb = tenpb;
	}
}