package ivs.thai.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class ThanhtichKiluat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thanhtich_kiluat.id
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thanhtich_kiluat.manv
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    private String manv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thanhtich_kiluat.loai
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    private Boolean loai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thanhtich_kiluat.lydo
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    private String lydo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thanhtich_kiluat.ngayghinhan
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    private Date ngayghinhan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thanhtich_kiluat.id
     *
     * @return the value of thanhtich_kiluat.id
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thanhtich_kiluat.id
     *
     * @param id the value for thanhtich_kiluat.id
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thanhtich_kiluat.manv
     *
     * @return the value of thanhtich_kiluat.manv
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public String getManv() {
        return manv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thanhtich_kiluat.manv
     *
     * @param manv the value for thanhtich_kiluat.manv
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public void setManv(String manv) {
        this.manv = manv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thanhtich_kiluat.loai
     *
     * @return the value of thanhtich_kiluat.loai
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public Boolean getLoai() {
        return loai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thanhtich_kiluat.loai
     *
     * @param loai the value for thanhtich_kiluat.loai
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public void setLoai(Boolean loai) {
        this.loai = loai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thanhtich_kiluat.lydo
     *
     * @return the value of thanhtich_kiluat.lydo
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public String getLydo() {
        return lydo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thanhtich_kiluat.lydo
     *
     * @param lydo the value for thanhtich_kiluat.lydo
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public void setLydo(String lydo) {
        this.lydo = lydo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thanhtich_kiluat.ngayghinhan
     *
     * @return the value of thanhtich_kiluat.ngayghinhan
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    public Date getNgayghinhan() {
        return ngayghinhan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thanhtich_kiluat.ngayghinhan
     *
     * @param ngayghinhan the value for thanhtich_kiluat.ngayghinhan
     *
     * @mbg.generated Wed Aug 21 20:05:14 ICT 2019
     */
    public void setNgayghinhan(Date ngayghinhan) {
        this.ngayghinhan = ngayghinhan;
    }
}