package ivs.thai.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.user_id
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.username
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.manv
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private String manv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.enable
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	private Boolean enable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.user_id
	 * @return  the value of user.user_id
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.user_id
	 * @param userId  the value for user.user_id
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.username
	 * @return  the value of user.username
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.username
	 * @param username  the value for user.username
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.manv
	 * @return  the value of user.manv
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public String getManv() {
		return manv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.manv
	 * @param manv  the value for user.manv
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setManv(String manv) {
		this.manv = manv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.enable
	 * @return  the value of user.enable
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public Boolean getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.enable
	 * @param enable  the value for user.enable
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	public void setEnable(Boolean enable) {
		this.enable = enable;
	}
//	public Set<AppRole> getRoles()
//	{
//		
//	}
}