package ivs.thai.myBatis.Mapper;

import ivs.thai.model.Nhanvien;
import ivs.thai.model.NhanvienExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NhanvienMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	long countByExample(NhanvienExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int deleteByExample(NhanvienExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int deleteByPrimaryKey(String manv);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int insert(Nhanvien record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int insertSelective(Nhanvien record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	List<Nhanvien> selectByExample(NhanvienExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	Nhanvien selectByPrimaryKey(String manv);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") Nhanvien record, @Param("example") NhanvienExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByExample(@Param("record") Nhanvien record, @Param("example") NhanvienExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByPrimaryKeySelective(Nhanvien record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table nhanvien
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByPrimaryKey(Nhanvien record);
	
}