package ivs.thai.myBatis.Mapper;

import ivs.thai.model.Phongban;
import ivs.thai.model.PhongbanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhongbanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	long countByExample(PhongbanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int deleteByExample(PhongbanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int deleteByPrimaryKey(String mapb);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int insert(Phongban record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int insertSelective(Phongban record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	List<Phongban> selectByExample(PhongbanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	Phongban selectByPrimaryKey(String mapb);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByExampleSelective(@Param("record") Phongban record, @Param("example") PhongbanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByExample(@Param("record") Phongban record, @Param("example") PhongbanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByPrimaryKeySelective(Phongban record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table phongban
	 * @mbg.generated  Wed Aug 21 20:05:14 ICT 2019
	 */
	int updateByPrimaryKey(Phongban record);
}